### ISSUE TITLE
REPORTE PDF

### ISSUE THREAD

**Issue by Edwin38H** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-edwin38h#1]
[Conexión de base de datos.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-edwin38h/files/6766999/Conexion.de.base.de.datos.pdf)

**Comment by CxrlosMX** [comment]
Calificación obtenida: 20
Excelente trabajo compañeros

**Comment by josealfredo79** [comment]
Bien hecho y rerevisado
